// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhBouyZwRwojzY-J-zE01JpYfY5CRdCi4',
    appId: '1:167364114932:web:1ccabd958f68f00c7421a1',
    messagingSenderId: '167364114932',
    projectId: 'napontadolapis-4311a',
    authDomain: 'napontadolapis-4311a.firebaseapp.com',
    storageBucket: 'napontadolapis-4311a.firebasestorage.app',
    measurementId: 'G-91P1G6S9TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfPHrcgKlUfyrzzplge9ArBMicJcb460M',
    appId: '1:167364114932:android:12dac9b3be22ab6a7421a1',
    messagingSenderId: '167364114932',
    projectId: 'napontadolapis-4311a',
    storageBucket: 'napontadolapis-4311a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzIlRtii9ed7iriSCVtFZHgF_ATE7ILlw',
    appId: '1:167364114932:ios:7ca3383cdb4f48167421a1',
    messagingSenderId: '167364114932',
    projectId: 'napontadolapis-4311a',
    storageBucket: 'napontadolapis-4311a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzIlRtii9ed7iriSCVtFZHgF_ATE7ILlw',
    appId: '1:167364114932:ios:7ca3383cdb4f48167421a1',
    messagingSenderId: '167364114932',
    projectId: 'napontadolapis-4311a',
    storageBucket: 'napontadolapis-4311a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhBouyZwRwojzY-J-zE01JpYfY5CRdCi4',
    appId: '1:167364114932:web:394aa9955fcc213d7421a1',
    messagingSenderId: '167364114932',
    projectId: 'napontadolapis-4311a',
    authDomain: 'napontadolapis-4311a.firebaseapp.com',
    storageBucket: 'napontadolapis-4311a.firebasestorage.app',
    measurementId: 'G-PCQG2R9BSK',
  );
}
